server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${YOUTUBE_DB_NAME}?${DB_PROPERTIES}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

auth:
  google:
    base-url: ${GOOGLE_BASE_URL}
    client-id: ${GOOGLE_CLIENT}
    redirect-url: ${GOOGLE_REDIRECT}

jwt:
  refresh-time: 2592000000 # 30일
  access-time: 3600000 # 1시간
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT_SECRET}

cloud:
  aws:
    s3:
      bucket: ${AWS_BUKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      instance-profile: true
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error